services:
- type: web
  name: redwood-api
  env: node
  buildCommand: yarn && yarn rw prisma migrate deploy && yarn rw build api
  startCommand: cd api && yarn api-server --functions ./dist/functions
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: redwood-db
      property: connectionString

- type: web
  name: redwood-web
  env: static
  buildCommand: yarn && yarn rw build web
  staticPublishPath: ./web/dist
  routes:
  - type: rewrite
    source: /.redwood/functions
    destination: replace_me_with_api_url
  - type: rewrite
    source: /*
    destination: /index.html

databases:
- name: redwood-db
