services:
- type: web
  name: redwood-test-cli-web
  env: static
  buildCommand: yarn && yarn rw build web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 14
  routes:
  - type: rewrite
    source: /.redwood/functions
    destination: replace_me_with_api_url
  - type: rewrite
    source: /*
    destination: /index.html

- type: web
  name: redwood-test-cli-api
  env: node
  buildCommand: yarn && yarn rw prisma migrate deploy && yarn rw build api
  startCommand: cd api && yarn api-server --functions ./dist/functions
  envVars:
  - key: NODE_VERSION
    value: 14
  - key: DATABASE_URL
    value: /data/sqlite.db
  # disk:
  #   name: sqlite-data
  #   mountPath: /data
  #   sizeGB: 1
